print("Getting to know you!")

UserName = input("Enter your name: ")
FavFood = input("Enter your favorite food: ")
FavMusic = input("Enter your favorite music genre: ")
Location = input("Enter your location: ")

print("You are ")
print(UserName)
print()
print("Your favorite food is ")
print(FavFood)
print()
print("Your favorite music genre is ")
print(FavMusic)
print()
print("You are from ")
print(Location)
print()
print("Nice to meet you, ")
print(UserName)
print("I hope you enjoy your day!")
